<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3  # This ensures 3 copies are always running
  selector:
    matchLabels:
      app: my-flask-api
  template:
    metadata:
      labels:
        app: my-flask-api
    spec:
      containers:
      - name: flask-container
        image: johnxyn/ci_cd_python:latest # K8s pulls this from Docker Hub
        env:
          - name: APP_COLOR
            value: "blue"
          - name: CUSTOM_MESSAGE
            value: "Hello from Kubernetes Config!"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3  # This ensures 3 copies are always running
  selector:
    matchLabels:
      app: my-flask-api
  template:
    metadata:
      labels:
        app: my-flask-api
    spec:
      containers:
      - name: flask-container
        image: johnxyn/ci_cd_python:latest # K8s pulls this from Docker Hub
        env:
          - name: APP_COLOR
            value: "blue"
          - name: CUSTOM_MESSAGE
            value: "Hello from Kubernetes Config!"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

>>>>>>> 5cacd72 (first commit)
