apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer # This gives you a public-facing IP address
  selector:
    app: my-flask-api
  ports:
    - protocol: TCP
      port: 80        # The port the world sees
      targetPort: 5000 # The port the app is listening on inside the container
